[env:inkplate10]
platform = espressif32 @ 6.11.0
board = esp32dev
framework = arduino

; CPU Frequency
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv

; Serial Monitor options
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder, default

; Critical: unset ESP32_DEV to prevent library confusion
build_unflags =
    -DARDUINO_ESP32_DEV

; Build options - PSRAM support
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_INKPLATE10
    -DCONFIG_FREERTOS_CHECK_STACKOVERFLOW_PTRVAL

; Library dependencies
lib_deps =
    https://github.com/SolderedElectronics/Inkplate-Arduino-library#10.2.1
    knolleary/PubSubClient@^2.8
    arduino-libraries/NTPClient@^3.2.1
    fbiego/ESP32Time@^2.0.6
    jchristensen/Timezone@^1.2.4
